# Generated by Django 4.0.4 on 2022-06-17 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_user', models.CharField(db_index=True, max_length=100, verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Символьный код (на английском)')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Обложка')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.act', verbose_name='Действие')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_product', to=settings.AUTH_USER_MODEL, verbose_name='Владелец объявления')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.category', verbose_name='Категория')),
                ('readers', models.ManyToManyField(blank=True, related_name='readers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='SliderFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.ImageField(blank=True, upload_to='sliders/%Y/%m/%d/', verbose_name='Слайд')),
                ('slide_one', models.ImageField(blank=True, upload_to='sliders/%Y/%m/%d/', verbose_name='Главный_слайд')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('activ', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Слайд фронт',
                'verbose_name_plural': 'Слайды фронт',
            },
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ava', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Аватар')),
                ('name_author', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname_author', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('place_work', models.CharField(choices=[('Пресса', 'Пресса'), ('Подготовительный участок', 'Подготовительный участок'), ('Токарка', 'Токарка'), ('ОТК', 'ОТК'), ('Радиалки', 'Радиалки'), ('Грибки', 'Грибки'), ('Роботы', 'Роботы'), ('Рубка', 'Рубка'), ('Стройка', 'Стройка'), ('Механики', 'Механики'), ('Электрики', 'Электрики'), ('Административный участок', 'Административный участок'), ('Дизайнеры', 'Дизайнеры'), ('Производство пп и матов', 'Производство пп и матов'), ('Производство пасты', 'Производство пасты'), ('Типография', 'Типография'), ('Склад гот. продукции', 'Склад гот. продукции'), ('Склад вулканизации', 'Склад вулканизации'), ('Упаковка', 'Упаковка'), ('Инструменталка', 'Инструменталка'), ('Менеджеры', 'Менеджеры'), ('Бухгалтерия', 'Бухгалтерия'), ('Обучающий центр', 'Обучающий центр'), ('Гараж', 'Гараж'), ('Химия', 'Химия'), ('Жгуты', 'Жгуты'), ('IT-отдел', 'IT-отдел')], max_length=255, verbose_name='Участок работы')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('master', models.BooleanField(default=False, verbose_name='Мастер участка')),
                ('author_products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.product', verbose_name='Автор продукта')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Фотоальбом')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.product', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомы',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('text', models.TextField(verbose_name='Добавить комментарий')),
                ('status', models.BooleanField(default=False, verbose_name='Видимость статьи')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('product_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_product', to='ads.product', verbose_name='key')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
